apiVersion: v1
kind: Service
metadata:
  name: commands-cluster-service
  namespace: ch-micro-service
spec:
  type: ClusterIP
  selector:
    app: commandservice
  ports:
    - name: commandservice
      protocol: TCP
      port: 80
      targetPort: 80
