apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
  namespace: ch-micro-service
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
